Add test for php modules
[#172080300]

diff --git a/tasks/test-dependency/php/run b/tasks/test-dependency/php/run
--- a/tasks/test-dependency/php/run
+++ b/tasks/test-dependency/php/run
@@ -3,11 +3,39 @@
 set -euo pipefail
 
 parent_dir="$(cd "$(dirname "$0")" && pwd)"
+major_minor_version=
 
 extract_tarball() {
   rm -rf php
   mkdir php
   tar -xf dependency/*.tgz -C php
+}
+
+configure_php() {
+  extension_dir="$(find "$PWD/php/lib/php/extensions" -name "no-debug-non-zts-*")"
+  major_minor_version="$(./php/bin/php --version | head -1 | cut -d' ' -f2 | cut -d '.' -f1-2 | sed 's/\./-/')"
+
+  sed \
+    -i \
+    "s|extension_dir=.*|extension_dir='${extension_dir}'|" \
+    "php/bin/php-config"
+
+  sed \
+    "s|REPLACE_ME_EXTENSION_DIR|${extension_dir}|" \
+    "${parent_dir}/fixtures/php.ini.template" \
+    > "$PWD/php/etc/php.ini"
+
+  <"${parent_dir}/fixtures/${major_minor_version}/extensions.json" \
+    jq -r .extensions[] | \
+    sed 's/[",\,]//g' | \
+    xargs -I {} echo "extension={}" >> "$PWD/php/etc/php.ini"
+
+  <"${parent_dir}/fixtures/${major_minor_version}/extensions.json" \
+    jq -r .zend_extensions[] | \
+    sed 's/[",\,]//g' | \
+    xargs -I {} echo "zend_extension={}" >> "$PWD/php/etc/php.ini"
+
+  export LD_LIBRARY_PATH="\$LD_LIBRARY_PATH:$PWD/php/lib"
 }
 
 check_version() {
@@ -19,7 +47,7 @@ check_version() {
   fi
 }
 
-check_server() {
+check_php_parsing() {
   set +e
 
   ./php/bin/php -f "${parent_dir}/fixtures/hello.php" > output.html
@@ -35,10 +63,29 @@ check_server() {
   set -e
 }
 
+check_installed_modules() {
+  set +e
+
+  ./php/bin/php -c "$PWD/php/etc/php.ini" -m > modules.txt
+
+  diff "${parent_dir}/fixtures/${major_minor_version}/expected-modules.txt" modules.txt > diff.txt
+  succeeded="$?"
+
+  if [[ ! "${succeeded}" ]]; then
+    echo "Could not find all expected modules. Diff:"
+    printf diff.txt
+    exit 1
+  fi
+
+  set -e
+}
+
 main() {
   extract_tarball
+  configure_php
   check_version "$1"
-  check_server
+  check_php_parsing
+  check_installed_modules
 
   echo "All tests passed!"
 }
