Fix tagging for cnb-builder releases.
Fix pipeline resources.

[#171364491]

Co-authored-by: Marty Spiewak <mspiewak@pivotal.io>

diff --git a/tasks/write-tags-list/run b/tasks/write-tags-list/run
--- a/tasks/write-tags-list/run
+++ b/tasks/write-tags-list/run
@@ -4,7 +4,11 @@ set -euo pipefail
 
 if [[ -d "platform-api-version" ]]; then
   platform_api_version="$(cat platform-api-version/version)"
-  echo "platform-api-${platform_api_version} " > tags/tags
+  if [[ "${STACK}" == "" ]]; then
+    echo "error: must set STACK param in pipeline config with platform-api-version"
+    exit 1
+  fi
+  echo "${STACK}-platform-api-${platform_api_version} " > tags/tags
 fi
 
 if [[ -d "version" ]]; then
